# -*- coding: utf-8 -*-
"""initials.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zurhAtcZv73YG_RxMyeH76klidCLhXvs
"""

# File: initials.py
# Description: Print out my initials JKK in block letters.
# Assignment Number: 2
#
# Name: Jeffery Kwasi Koomson
# STUDENT ID: 2425401045
# Email:2425401045@live.gctu.edu.gh
# Grader:Augustus Buckman
#
# On my honor, Jeffery Kwasi Koomson, this programming assignment is my own work
# and I have not provided this code to any other student.


def main():
    # This is the main the main function

    print()
    print("...JKK")
    print()
    print(".......JJJJJJ..........KK.....KK...........KK.....KK........")
    print(".......JJJJJJ..........KK....KK............KK....KK.........")
    print(".........JJ............KK...KK.............KK...KK..........")
    print(".........JJ............KK..KK..............KK..KK...........")
    print(".........JJ............KKKKK...............KKKKK............")
    print(".........JJ............KKKKK...............KKKKK............")
    print(".........JJ............KK..KK..............KK..KK...........")
    print("...J.....JJ............KK...KK.............KK...KK..........")
    print("...JJ....JJ.......**...KK....KK.......**...KK....KK.......**")
    print("....JJJJJJ........**...KK.....KK......**...KK.....KK......**")
    print()


main()